name: format

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: git pull
      - run: |
          npm i
          npm run format
          git --no-pager diff
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: `npm run format`"
