name: Resume

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RELEASE_APP_ID: 795363
  RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
  PJ_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: resume-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.RELEASE_APP_ID }}
          private-key: ${{ env.RELEASE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "17"
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          libasound2t64 libasound2-dev libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
          fonts-liberation libayatana-appindicator3-1 libnss3 lsb-release xdg-utils wget pdftk chromium-browser
      - run: npm install
      - run: |
          mkdir -p generated
          check_pdf_generation() {
            local pdf_file="$1"
            if [ ! -f "$pdf_file" ] || ! pdftk "$pdf_file" dump_data > /dev/null 2>&1; then
              ls -la generated
              echo "Error: PDF generation failed or produced invalid PDF: $pdf_file"
              return 1
            fi
            echo "Successfully generated and validated: $pdf_file"
          }
          export PUPPETEER_ARGS="--no-sandbox --disable-setuid-sandbox"
          export PUPPETEER_LAUNCH_ARGS="--no-sandbox --disable-setuid-sandbox"
          export PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"

          echo "Current directory contents before generation:"
          ls -la generated/resume/

          npm run generate:en
          check_pdf_generation "generated/HiromiShikata-FullStack-Engineer-and-Manager.resume.full.en.pdf"
          npm run generate:ja
          check_pdf_generation "generated/HiromiShikata-FullStack-Engineer-and-Manager.resume.full.ja.pdf"
          sed 's@志方\|シカタ\|裕美\|ヒロミ@*****@g' generated/resume.full.ja.yaml > generated/resume.full.ja.masked.yaml
          npm run generate:resume --file=resume.full.ja.masked",
          check_pdf_generation "generated/HiromiShikata-FullStack-Engineer-and-Manager.resume.full.ja.masked.pdf"

          echo "Current directory contents after generation:"
          ls -la generated

          for html_file in generated/*.html; do
            sed -i '/<head>/a \  <!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({"gtm.start":\nnew Date().getTime(),event:"gtm.js"});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!="dataLayer"?"&l="+l:"";j.async=true;j.src=\n"https://www.googletagmanager.com/gtm.js?id="+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,"script","dataLayer","GTM-NH7SBSVG");</script>\n<!-- End Google Tag Manager -->' "$html_file"
            sed -i '/<body>/a \  <!-- Google Tag Manager (noscript) -->\n<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NH7SBSVG"\nheight="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->' "$html_file"
          done
          npm run format

          echo "Git status:"
          git status
      - run: git config --global user.email "gh-actions"
      - run: git config --global user.name "gh-actions"
      - if: github.ref == 'refs/heads/main'
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "autogen: release [ci skip]"
            git push --force origin main
          fi

      - run: |
          if [ $(pdftk generated/resume/HiromiShikata.resume.short.pdf dump_data | grep NumberOfPages | awk '{print $2}') -ne 1 ]; then
            echo "Resume must be exactly 1 page"
            exit 1
          fi
