name: Resume

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "17"
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          libasound2t64 libasound2-dev libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
          fonts-liberation libayatana-appindicator3-1 libnss3 lsb-release xdg-utils wget pdftk chromium-browser
      - run: npm install
      - run: |
          mkdir -p generated/resume
          check_pdf_generation() {
            local pdf_file="$1"
            if [ ! -f "$pdf_file" ] || ! pdftk "$pdf_file" dump_data > /dev/null 2>&1; then
              echo "Error: PDF generation failed or produced invalid PDF: $pdf_file"
              return 1
            fi
            echo "Successfully generated and validated: $pdf_file"
          }
          export PUPPETEER_ARGS="--no-sandbox --disable-setuid-sandbox"
          export PUPPETEER_LAUNCH_ARGS="--no-sandbox --disable-setuid-sandbox"
          export PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"

          echo "Current directory contents before generation:"
          ls -la generated/resume/

          npm run generate-from-json --output_dir=generated/resume --file=resume.short
          check_pdf_generation "generated/resume/HiromiShikata.resume.short.pdf"
          npm run generate-from-json --output_dir=generated/resume --file=resume.full
          check_pdf_generation "generated/resume/HiromiShikata.resume.full.pdf"
          npm run generate-from-json --output_dir=generated/resume --file=resume.ja.full
          check_pdf_generation "generated/resume/HiromiShikata.resume.ja.full.pdf"

          echo "Current directory contents after generation:"
          ls -la generated/resume/

          for html_file in generated/resume/*.html; do
            sed -i '/<head>/a \  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ES8HLN40E3"></script>\n  <script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('\''js'\'', new Date());\n  gtag('\''config'\'', '\''G-ES8HLN40E3'\'');\n  </script>' "$html_file"
          done

          echo "Git status:"
          git status

          sed 's@"志方 裕美"@"********"@g' RESUME.ja.md > generated/RESUME.masked-name.ja.md

          echo "Adding generated files to git:"
          git add generated/
          git status

      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update generated resume files"
          file_pattern: "generated"

      - run: |
          if [ $(pdftk generated/resume/HiromiShikata.resume.short.pdf dump_data | grep NumberOfPages | awk '{print $2}') -ne 1 ]; then
            echo "Resume must be exactly 1 page"
            exit 1
          fi
